# Generated by Django 5.0.9 on 2024-10-13 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorregistry',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='doctorregistry',
            name='registry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.registry'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='registries',
            field=models.ManyToManyField(through='doctors.DoctorRegistry', to='registry.registry'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='organizations',
            field=models.ManyToManyField(to='doctors.organization'),
        ),
    ]
