# Generated by Django 5.0.9 on 2024-10-13 15:04

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Nombre')),
                ('father_last_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Apellido Paterno')),
                ('mother_last_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Apellido Materno')),
                ('married_last_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Apellido de Casada')),
                ('full_name', models.CharField(blank=True, editable=False, max_length=256, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('gender', models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer'), ('O', 'Otro')], max_length=128, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ocupation', models.CharField(blank=True, max_length=128, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=128, null=True)),
                ('refered_by', models.CharField(blank=True, max_length=128, null=True)),
                ('alergies', models.CharField(blank=True, max_length=128, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=128, null=True)),
                ('religion', models.CharField(blank=True, max_length=128, null=True)),
                ('file_number', models.PositiveIntegerField(blank=True, null=True)),
                ('legacy_id', models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True)),
                ('comments', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('alerts', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('family_health_history', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('personal_pathological_health_history', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('personal_health_history', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('gynecological_health_history', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='doctors.doctor', verbose_name='Médico Tratante')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('street', models.CharField(blank=True, max_length=256, null=True, verbose_name='Calle')),
                ('neighborhood', models.CharField(blank=True, max_length=128, null=True, verbose_name='Colonia')),
                ('county', models.CharField(blank=True, max_length=128, null=True, verbose_name='Del/Mpio')),
                ('state', models.CharField(blank=True, max_length=128, null=True, verbose_name='Estado')),
                ('zip_code', models.CharField(blank=True, max_length=128, null=True, verbose_name='CP')),
                ('country', models.CharField(blank=True, default='México', max_length=128, null=True, verbose_name='País')),
                ('legacy_id', models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='Paciente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=256, null=True)),
                ('type_of', models.CharField(blank=True, choices=[('Celular', 'Celular'), ('Casa', 'Casa'), ('Oficina', 'Oficina'), ('Recados', 'Recados'), ('Biper', 'Biper'), ('Otro', 'Otro')], default='Celular', max_length=128, null=True)),
                ('legacy_id', models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
