# Generated by Django 5.0.9 on 2024-10-13 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='alergies',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='alerts',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='family_health_history',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gynecological_health_history',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='legacy_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ocupation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='personal_health_history',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='personal_pathological_health_history',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='refered_by',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='religion',
        ),
        migrations.AddField(
            model_name='patient',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='doctors.organization', verbose_name='Organizacion'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='file_number',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Numero de Expediente'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
