# Generated by Django 5.0.9 on 2024-10-13 15:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='Nombre')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Variable',
                'verbose_name_plural': 'Variables',
            },
        ),
        migrations.CreateModel(
            name='ChoiceVariable',
            fields=[
                ('variable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogs.variable')),
                ('type_of', models.CharField(blank=True, choices=[('SINGLE', 'Seleccion Unica'), ('MULTIPLE', 'Seleccion Multiple')], default='SINGLE', max_length=16, null=True, verbose_name='Tipo de Seleccion')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('catalogs.variable',),
        ),
        migrations.CreateModel(
            name='FileVariable',
            fields=[
                ('variable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogs.variable')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('catalogs.variable',),
        ),
        migrations.CreateModel(
            name='NumberVariable',
            fields=[
                ('variable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogs.variable')),
                ('max_limit', models.CharField(blank=True, max_length=128, null=True, verbose_name='Maximo')),
                ('min_limit', models.CharField(blank=True, max_length=128, null=True, verbose_name='Minimo')),
                ('decima_places', models.PositiveSmallIntegerField(default=0)),
                ('unit', models.CharField(blank=True, max_length=128, null=True, verbose_name='Unidad')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('catalogs.variable',),
        ),
        migrations.CreateModel(
            name='TextVariable',
            fields=[
                ('variable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalogs.variable')),
                ('display', models.CharField(blank=True, choices=[('SINGLE', 'Una Linea'), ('MULTIPLE', 'Muchas Lineas')], default='SINGLE', max_length=128, null=True, verbose_name='Tipo de Vista')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('catalogs.variable',),
        ),
        migrations.CreateModel(
            name='ChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Nombre')),
                ('choice_variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.choicevariable')),
            ],
            options={
                'verbose_name': 'Opción',
                'verbose_name_plural': 'Opciones',
            },
        ),
    ]
